### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by s0ubhik** [primeseven1/Chris-Operating-System#1]
Hey, I am trying to build my own hobby operating system too but I am not able to find a source that talks about flat binary file loading... I show your recent activity on the mell-o-tron project, I really appreciate it. Can you help me

**Comment by primeseven1** [comment]
Yeah I can try to help you.

So first you would want to create some kind of file system, and then you would want to find the binary you want to load on the disk, and then you would load that into memory.

You would also probably want to set up a stack for the program you want to run, and then call the entry point.

That's how I would probably go about it, and I do know that nanobyte's YouTube channel does have a video for the FAT file system if you want to look at that, or you could even try to implement your own if you want, but I would still look at that video if you were to try to implement your own.

Reading from the disk would involve using the IO ports, and you can find the IO ports you need to use on the osdev wiki. There is also a resource for reading from the disk on osdev as well.

I hope this helps you out!

**Comment by s0ubhik** [comment]
Thanks a lot to add to my knowledge but reading my disk is not my where I am stuck. I could read and the disk and load to it head but I am not able to jump into the entry point it gives a (General Protection Fault) inturrpt 13, I think its due to the GDT, You can look into my code https://github.com/s0ubhik/myos

```c
 void (*func_ptr)(void) = (void (*)(void))0x600000;
 func_ptr();
```
I loaded my the binary at `0x6000000` and then jumped like this it gave 

![7rWvd](https://github.com/primeseven1/Chris-Operating-System/assets/55374257/9160d7a8-fa4b-4e10-bcce-5c0826f6e475)
I hope I was able to describe my problem. 
Thank you

**Comment by primeseven1** [comment]
Looking at your GDT, it looks like your segment limits may be too big, try making your segment limit 0xFFFFF instead

**Comment by s0ubhik** [comment]
Yes, It had multiple reasons ome of them was the GDT segment limit, aslo I have to setup GDT TSS before jumping around address
